#!/bin/bash

# =============================================================================
# NetBird Self-Hosted - PocketID IDP Functions
# =============================================================================
# Utility functions for PocketID identity provider configuration
# =============================================================================

# -----------------------------------------------------------------------------
# PocketID Configuration
# -----------------------------------------------------------------------------

# PocketID-specific OIDC endpoint pattern
IDP_OIDC_PATTERN="/.well-known/openid-configuration"

# PocketID device auth provider setting
IDP_DEVICE_AUTH_PROVIDER="none"

# PocketID scopes
IDP_SCOPES="openid profile email groups offline_access"

# PocketID token source
IDP_TOKEN_SOURCE="idToken"

# -----------------------------------------------------------------------------
# Common OIDC Endpoint Builder
# -----------------------------------------------------------------------------

build_oidc_endpoint() {
    local idp_url="$1"

    # Remove trailing slash from URL
    idp_url="${idp_url%/}"

    echo "${idp_url}${IDP_OIDC_PATTERN}"
}

# -----------------------------------------------------------------------------
# Management.json IdpManagerConfig Generator
# -----------------------------------------------------------------------------

generate_idp_manager_config_pocketid() {
    local client_id="$1"
    local api_token="$2"
    local mgmt_endpoint="$3"

    cat << EOF
    "IdpManagerConfig": {
        "ManagerType": "pocketid",
        "ClientID": "${client_id}",
        "Extra": {
            "ManagementEndpoint": "${mgmt_endpoint}",
            "ApiToken": "${api_token}"
        }
    }
EOF
}

# -----------------------------------------------------------------------------
# Device Authorization Flow Generator
# -----------------------------------------------------------------------------

generate_device_auth_flow() {
    cat << EOF
    "DeviceAuthorizationFlow": {
        "Provider": "none"
    }
EOF
}

# -----------------------------------------------------------------------------
# Dashboard.env Generator
# -----------------------------------------------------------------------------

generate_dashboard_env() {
    local netbird_domain="$1"
    local idp_url="$2"
    local client_id="$3"

    cat << EOF
# =============================================================================
# NetBird Dashboard - Environment Configuration
# =============================================================================
# Generated by setup.sh on $(date)
# Identity Provider: PocketID
# =============================================================================

# Endpoints
NETBIRD_MGMT_API_ENDPOINT=https://${netbird_domain}
NETBIRD_MGMT_GRPC_API_ENDPOINT=https://${netbird_domain}

# OIDC Configuration
AUTH_AUDIENCE=${client_id}
AUTH_CLIENT_ID=${client_id}
AUTH_AUTHORITY=${idp_url}
USE_AUTH0=false
AUTH_SUPPORTED_SCOPES=${IDP_SCOPES}
AUTH_REDIRECT_URI=/auth
AUTH_SILENT_REDIRECT_URI=/silent-auth

# Token Configuration
NETBIRD_TOKEN_SOURCE=${IDP_TOKEN_SOURCE}

# SSL Configuration
NGINX_SSL_PORT=443
LETSENCRYPT_DOMAIN=none
EOF
}

# -----------------------------------------------------------------------------
# Utility: Check if IDP URL is reachable
# -----------------------------------------------------------------------------

check_idp_connectivity() {
    local idp_url="$1"
    local oidc_endpoint="$2"

    print_step "Checking IDP connectivity..."

    if curl -s --max-time 10 "${oidc_endpoint}" > /dev/null 2>&1; then
        print_success "IDP OIDC endpoint is reachable"
        return 0
    else
        print_warning "Could not reach OIDC endpoint: ${oidc_endpoint}"
        print_info "Make sure your IDP is running and accessible"
        return 1
    fi
}
